2025-06-29T17:35:53 {"cpu": 0.353515625, "cpu_total": 6, "cpu_usage": 0.058919270833333336, "memory": 2035.0, "memory_total": 9990.0, "memory_usage": 0.2037037037037037, "pipeline_run_id": 3, "pipeline_schedule_id": 4, "pipeline_uuid": "elt_proj_breweries", "hostname": "5d4149a01f25", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 3 in schedule 4 is alive.", "timestamp": 1751218553.312663, "uuid": "26833bc4d8644e1ead9f8e379a11054a"}
2025-06-29T17:35:53 {"cpu": 0.353515625, "cpu_total": 6, "cpu_usage": 0.058919270833333336, "memory": 2051.0, "memory_total": 9990.0, "memory_usage": 0.2053053053053053, "pipeline_run_id": 3, "pipeline_schedule_id": 4, "pipeline_uuid": "elt_proj_breweries", "hostname": "5d4149a01f25", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 3 in schedule 4 is alive.", "timestamp": 1751218553.519902, "uuid": "e22d2d035f7d42f6a3e678148785b114"}
2025-06-29T17:35:53 {"block_run_id": 17, "block_uuid": "import_data_api", "pipeline_run_id": 3, "pipeline_schedule_id": 4, "pipeline_uuid": "elt_proj_breweries", "hostname": "5d4149a01f25", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 17: pipeline elt_proj_breweries block import_data_api", "timestamp": 1751218553.612743, "uuid": "6ee477218bb7416f971e21045fa23ef8"}
2025-06-29T17:36:01 {"cpu": 0.349609375, "cpu_total": 6, "cpu_usage": 0.058268229166666664, "memory": 2227.0, "memory_total": 9990.0, "memory_usage": 0.22292292292292293, "pipeline_run_id": 3, "pipeline_schedule_id": 4, "pipeline_uuid": "elt_proj_breweries", "hostname": "5d4149a01f25", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 3 in schedule 4 is alive.", "timestamp": 1751218561.528843, "uuid": "eb1772071bb841a0abff231896134831"}
2025-06-29T17:36:09 {"block_run_id": 17, "block_uuid": "import_data_api", "pipeline_run_id": 3, "pipeline_schedule_id": 4, "pipeline_uuid": "elt_proj_breweries", "hostname": "5d4149a01f25", "level": "INFO", "message": "BlockRun 17 (block_uuid: import_data_api) completes.", "timestamp": 1751218569.976842, "uuid": "8b39db2eb36a4647b06e2cfda7b31e47"}
2025-06-29T17:36:11 {"cpu": 0.3837890625, "cpu_total": 6, "cpu_usage": 0.06396484375, "memory": 2023.0, "memory_total": 9990.0, "memory_usage": 0.2025025025025025, "pipeline_run_id": 3, "pipeline_schedule_id": 4, "pipeline_uuid": "elt_proj_breweries", "hostname": "5d4149a01f25", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 3 in schedule 4 is alive.", "timestamp": 1751218571.74667, "uuid": "c422520b3077450fb396ab4071e0d700"}
2025-06-29T17:36:12 {"block_run_id": 18, "block_uuid": "brewery_bronze_export", "pipeline_run_id": 3, "pipeline_schedule_id": 4, "pipeline_uuid": "elt_proj_breweries", "hostname": "5d4149a01f25", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 18: pipeline elt_proj_breweries block brewery_bronze_export", "timestamp": 1751218572.016002, "uuid": "fb3588056fc34fec9db11f8e2c09fde8"}
2025-06-29T17:36:12 {"block_run_id": 18, "block_uuid": "brewery_bronze_export", "pipeline_run_id": 3, "pipeline_schedule_id": 4, "pipeline_uuid": "elt_proj_breweries", "hostname": "5d4149a01f25", "level": "EXCEPTION", "message": "BlockRun 18 (block_uuid: brewery_bronze_export) failed.", "timestamp": 1751218572.353205, "uuid": "9a132e6c642144358966e318635e45cf", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1691, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1570, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1910, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2073, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2169, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 25, in export_data_to_s3\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/s3.py\", line 103, in export\n    format = self._get_file_format(object_key)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py\", line 150, in _get_file_format\n    return FileFormat.from_extension(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py\", line 68, in from_extension\n    raise ValueError(\nValueError: None file format found for this file extension: \n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1442, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1226, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 794, in invoke\n    return callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 108, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 60, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1730, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 333, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 640, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 122, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 199, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 353, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 317, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1235, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 464, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "None file format found for this file extension: "}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1691, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1570, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1910, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2073, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2169, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 25, in export_data_to_s3
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/s3.py", line 103, in export
    format = self._get_file_format(object_key)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py", line 150, in _get_file_format
    return FileFormat.from_extension(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py", line 68, in from_extension
    raise ValueError(
ValueError: None file format found for this file extension: 
2025-06-29T17:36:22 {"cpu": 0.384765625, "cpu_total": 6, "cpu_usage": 0.06412760416666667, "memory": 2023.0, "memory_total": 9990.0, "memory_usage": 0.2025025025025025, "pipeline_run_id": 3, "pipeline_schedule_id": 4, "pipeline_uuid": "elt_proj_breweries", "hostname": "5d4149a01f25", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 3 in schedule 4 is alive.", "timestamp": 1751218582.032538, "uuid": "7b23ef393fc748b5b03ddc25d06ce30e"}
