2025-06-30T04:46:52 {"cpu": 0.169921875, "cpu_total": 6, "cpu_usage": 0.0283203125, "memory": 1407.0, "memory_total": 9990.0, "memory_usage": 0.14084084084084084, "pipeline_run_id": 34, "pipeline_schedule_id": 15, "pipeline_uuid": "elt_proj_breweries", "hostname": "55c2d9344d8d", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 34 in schedule 15 is alive.", "timestamp": 1751258812.414015, "uuid": "0c38a175f5794220b9858978df1ea1ce"}
2025-06-30T04:46:52 {"cpu": 0.169921875, "cpu_total": 6, "cpu_usage": 0.0283203125, "memory": 1440.0, "memory_total": 9990.0, "memory_usage": 0.14414414414414414, "pipeline_run_id": 34, "pipeline_schedule_id": 15, "pipeline_uuid": "elt_proj_breweries", "hostname": "55c2d9344d8d", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 34 in schedule 15 is alive.", "timestamp": 1751258812.693322, "uuid": "6060388e6ac94910aaab8684d528d4cc"}
2025-06-30T04:46:52 {"block_run_id": 100, "block_uuid": "import_data_api", "pipeline_run_id": 34, "pipeline_schedule_id": 15, "pipeline_uuid": "elt_proj_breweries", "hostname": "55c2d9344d8d", "level": "INFO", "message": "Execute PipelineRun 34, BlockRun 100: pipeline elt_proj_breweries block import_data_api", "timestamp": 1751258812.777868, "uuid": "f397ff4abc484a5183fb3f8d862117a0"}
2025-06-30T04:47:02 {"cpu": 0.1689453125, "cpu_total": 6, "cpu_usage": 0.028157552083333332, "memory": 1466.0, "memory_total": 9990.0, "memory_usage": 0.14674674674674676, "pipeline_run_id": 34, "pipeline_schedule_id": 15, "pipeline_uuid": "elt_proj_breweries", "hostname": "55c2d9344d8d", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 34 in schedule 15 is alive.", "timestamp": 1751258822.030533, "uuid": "8333bf84f0f342cca6ab2ced57e3fb93"}
2025-06-30T04:47:11 {"cpu": 0.1728515625, "cpu_total": 6, "cpu_usage": 0.02880859375, "memory": 1466.0, "memory_total": 9990.0, "memory_usage": 0.14674674674674676, "pipeline_run_id": 34, "pipeline_schedule_id": 15, "pipeline_uuid": "elt_proj_breweries", "hostname": "55c2d9344d8d", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 34 in schedule 15 is alive.", "timestamp": 1751258831.338739, "uuid": "dbbaded35f1d42608dfaa5e3d222da49"}
2025-06-30T04:47:21 {"cpu": 0.1708984375, "cpu_total": 6, "cpu_usage": 0.028483072916666668, "memory": 1471.0, "memory_total": 9990.0, "memory_usage": 0.14724724724724725, "pipeline_run_id": 34, "pipeline_schedule_id": 15, "pipeline_uuid": "elt_proj_breweries", "hostname": "55c2d9344d8d", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 34 in schedule 15 is alive.", "timestamp": 1751258841.568602, "uuid": "b403d60f51e946e6ab954a800054c92b"}
2025-06-30T04:47:31 {"cpu": 0.1689453125, "cpu_total": 6, "cpu_usage": 0.028157552083333332, "memory": 1478.0, "memory_total": 9990.0, "memory_usage": 0.14794794794794794, "pipeline_run_id": 34, "pipeline_schedule_id": 15, "pipeline_uuid": "elt_proj_breweries", "hostname": "55c2d9344d8d", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 34 in schedule 15 is alive.", "timestamp": 1751258851.85188, "uuid": "d2798a09e27c4f67a082a8e2842ca09f"}
2025-06-30T04:47:42 {"cpu": 0.19921875, "cpu_total": 6, "cpu_usage": 0.033203125, "memory": 1723.0, "memory_total": 9990.0, "memory_usage": 0.17247247247247247, "pipeline_run_id": 34, "pipeline_schedule_id": 15, "pipeline_uuid": "elt_proj_breweries", "hostname": "55c2d9344d8d", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 34 in schedule 15 is alive.", "timestamp": 1751258862.170488, "uuid": "634378f174b44e4888f2a25a8aa71ff8"}
2025-06-30T04:47:49 {"block_run_id": 100, "block_uuid": "import_data_api", "pipeline_run_id": 34, "pipeline_schedule_id": 15, "pipeline_uuid": "elt_proj_breweries", "hostname": "55c2d9344d8d", "level": "INFO", "message": "BlockRun 100 (block_uuid: import_data_api) completes.", "timestamp": 1751258869.709454, "uuid": "9cf99678b03643e5bd08b59bd5435151"}
2025-06-30T04:47:51 {"cpu": 0.20361328125, "cpu_total": 6, "cpu_usage": 0.033935546875, "memory": 1425.0, "memory_total": 9990.0, "memory_usage": 0.14264264264264265, "pipeline_run_id": 34, "pipeline_schedule_id": 15, "pipeline_uuid": "elt_proj_breweries", "hostname": "55c2d9344d8d", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 34 in schedule 15 is alive.", "timestamp": 1751258871.499312, "uuid": "14a130d4a5e54e6ead968f67608a02ad"}
2025-06-30T04:47:51 {"block_run_id": 101, "block_uuid": "brewery_bronze_export", "pipeline_run_id": 34, "pipeline_schedule_id": 15, "pipeline_uuid": "elt_proj_breweries", "hostname": "55c2d9344d8d", "level": "INFO", "message": "Execute PipelineRun 34, BlockRun 101: pipeline elt_proj_breweries block brewery_bronze_export", "timestamp": 1751258871.877074, "uuid": "6d810f4160b3477a9b4388e479ee4a70"}
2025-06-30T04:48:00 {"block_run_id": 101, "block_uuid": "brewery_bronze_export", "pipeline_run_id": 34, "pipeline_schedule_id": 15, "pipeline_uuid": "elt_proj_breweries", "hostname": "55c2d9344d8d", "level": "EXCEPTION", "message": "BlockRun 101 (block_uuid: brewery_bronze_export) failed.", "timestamp": 1751258880.540407, "uuid": "cf13aa9a595f45638d88c27fd5f7ced1", "error": "Traceback (most recent call last):\n  File \"<string>\", line 38, in export_data_to_s3\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/s3.py\", line 120, in export\n    self.client.put_object(Body=buffer, Bucket=bucket_name, Key=object_key)\n  File \"/usr/local/lib/python3.10/site-packages/botocore/client.py\", line 530, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/botocore/client.py\", line 964, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1691, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1570, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1910, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2073, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2169, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 55, in export_data_to_s3\nRuntimeError: [Falha Cr\u00edtica] N\u00e3o foi poss\u00edvel exportar os dados para s3://db-inbev-bronze-layer1/breweries_raw.json ap\u00f3s 3 tentativas.\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1442, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1226, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 794, in invoke\n    return callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 108, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 60, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1730, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 333, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 640, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 122, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 199, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 353, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 317, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1235, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 464, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "[Falha Cr\u00edtica] N\u00e3o foi poss\u00edvel exportar os dados para s3://db-inbev-bronze-layer1/breweries_raw.json ap\u00f3s 3 tentativas."}
Traceback (most recent call last):
  File "<string>", line 38, in export_data_to_s3
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/s3.py", line 120, in export
    self.client.put_object(Body=buffer, Bucket=bucket_name, Key=object_key)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1691, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1570, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1910, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2073, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2169, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 55, in export_data_to_s3
RuntimeError: [Falha Crítica] Não foi possível exportar os dados para s3://db-inbev-bronze-layer1/breweries_raw.json após 3 tentativas.
2025-06-30T04:48:01 {"cpu": 0.20654296875, "cpu_total": 6, "cpu_usage": 0.034423828125, "memory": 1416.0, "memory_total": 9990.0, "memory_usage": 0.14174174174174173, "pipeline_run_id": 34, "pipeline_schedule_id": 15, "pipeline_uuid": "elt_proj_breweries", "hostname": "55c2d9344d8d", "level": "INFO", "message": "Pipeline elt_proj_breweries for run 34 in schedule 15 is alive.", "timestamp": 1751258881.957084, "uuid": "23ff8d839a3e408d8beaf1090f953851"}
